# Generated by Django 5.1.7 on 2025-04-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appvarity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
